[2024-12-24 19:46:11,757] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: TwitterDAG.twitter_datascience scheduled__2024-12-23T00:00:00+00:00 [queued]>
[2024-12-24 19:46:11,767] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: TwitterDAG.twitter_datascience scheduled__2024-12-23T00:00:00+00:00 [queued]>
[2024-12-24 19:46:11,767] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-12-24 19:46:11,767] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-12-24 19:46:11,767] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-12-24 19:46:11,793] {taskinstance.py:1377} INFO - Executing <Task(TwitterOperator): twitter_datascience> on 2024-12-23 00:00:00+00:00
[2024-12-24 19:46:11,797] {standard_task_runner.py:52} INFO - Started process 982972 to run task
[2024-12-24 19:46:11,803] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'TwitterDAG', 'twitter_datascience', 'scheduled__2024-12-23T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpz87d1vy7', '--error-file', '/tmp/tmp14lbkht8']
[2024-12-24 19:46:11,805] {standard_task_runner.py:80} INFO - Job 15: Subtask twitter_datascience
[2024-12-24 19:46:11,874] {task_command.py:370} INFO - Running <TaskInstance: TwitterDAG.twitter_datascience scheduled__2024-12-23T00:00:00+00:00 [running]> on host ANDERSON.
[2024-12-24 19:46:11,981] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=TwitterDAG
AIRFLOW_CTX_TASK_ID=twitter_datascience
AIRFLOW_CTX_EXECUTION_DATE=2024-12-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-23T00:00:00+00:00
[2024-12-24 19:46:11,996] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dev/curso/airflow_pipeline/operators/twiter_operator.py", line 31, in execute
    for pg in TwiterHook(end_time, start_time, query).run():
  File "/home/dev/curso/airflow_pipeline/hook/twiter_hook.py", line 46, in run
    session = self.get_conn()
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `conexao` isn't defined
[2024-12-24 19:46:12,003] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=TwitterDAG, task_id=twitter_datascience, execution_date=20241223T000000, start_date=20241224T224611, end_date=20241224T224612
[2024-12-24 19:46:12,022] {standard_task_runner.py:92} ERROR - Failed to execute job 15 for task twitter_datascience (The conn_id `conexao` isn't defined; 982972)
[2024-12-24 19:46:12,057] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-12-24 19:46:12,079] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-24 19:49:52,492] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: TwitterDAG.twitter_datascience scheduled__2024-12-23T00:00:00+00:00 [queued]>
[2024-12-24 19:49:52,501] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: TwitterDAG.twitter_datascience scheduled__2024-12-23T00:00:00+00:00 [queued]>
[2024-12-24 19:49:52,501] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-12-24 19:49:52,501] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-12-24 19:49:52,501] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-12-24 19:49:52,520] {taskinstance.py:1377} INFO - Executing <Task(TwitterOperator): twitter_datascience> on 2024-12-23 00:00:00+00:00
[2024-12-24 19:49:52,522] {standard_task_runner.py:52} INFO - Started process 985288 to run task
[2024-12-24 19:49:52,529] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'TwitterDAG', 'twitter_datascience', 'scheduled__2024-12-23T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpkidiexlx', '--error-file', '/tmp/tmpci04di4u']
[2024-12-24 19:49:52,530] {standard_task_runner.py:80} INFO - Job 14: Subtask twitter_datascience
[2024-12-24 19:49:52,590] {task_command.py:370} INFO - Running <TaskInstance: TwitterDAG.twitter_datascience scheduled__2024-12-23T00:00:00+00:00 [running]> on host ANDERSON.
[2024-12-24 19:49:52,673] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=TwitterDAG
AIRFLOW_CTX_TASK_ID=twitter_datascience
AIRFLOW_CTX_EXECUTION_DATE=2024-12-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-23T00:00:00+00:00
[2024-12-24 19:49:52,682] {base.py:68} INFO - Using connection ID 'conexao' for task execution.
[2024-12-24 19:49:52,684] {twiter_hook.py:27} INFO - URL: https://labdados.com/2/tweets/search/recent?query=datascience&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,lang,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2024-12-23T00:00:00.00Z&end_time=2024-12-24T00:00:00.00Z
[2024-12-24 19:49:53,074] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=TwitterDAG, task_id=twitter_datascience, execution_date=20241223T000000, start_date=20241224T224952, end_date=20241224T224953
[2024-12-24 19:49:53,113] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-12-24 19:49:53,134] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
