[2024-12-14 15:51:25,387] {processor.py:153} INFO - Started process (PID=47758) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:51:25,388] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 15:51:25,389] {logging_mixin.py:115} INFO - [2024-12-14 15:51:25,389] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:51:25,450] {logging_mixin.py:115} INFO - [2024-12-14 15:51:25,450] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 15:51:25,450] {logging_mixin.py:115} INFO - [2024-12-14 15:51:25,450] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 15:51:25,451] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:51:25,501] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.118 seconds
[2024-12-14 15:52:03,652] {processor.py:153} INFO - Started process (PID=48267) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:52:03,653] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 15:52:03,653] {logging_mixin.py:115} INFO - [2024-12-14 15:52:03,653] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:52:03,673] {logging_mixin.py:115} INFO - [2024-12-14 15:52:03,673] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 15:52:03,673] {logging_mixin.py:115} INFO - [2024-12-14 15:52:03,673] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 15:52:03,674] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:52:03,689] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-12-14 15:52:35,816] {processor.py:153} INFO - Started process (PID=48381) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:52:35,817] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 15:52:35,818] {logging_mixin.py:115} INFO - [2024-12-14 15:52:35,818] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:52:35,840] {logging_mixin.py:115} INFO - [2024-12-14 15:52:35,840] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 15:52:35,841] {logging_mixin.py:115} INFO - [2024-12-14 15:52:35,841] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 15:52:35,841] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:52:35,855] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2024-12-14 15:53:08,901] {processor.py:153} INFO - Started process (PID=48501) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:53:08,903] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 15:53:08,904] {logging_mixin.py:115} INFO - [2024-12-14 15:53:08,904] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:53:08,929] {logging_mixin.py:115} INFO - [2024-12-14 15:53:08,928] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 15:53:08,929] {logging_mixin.py:115} INFO - [2024-12-14 15:53:08,929] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 15:53:08,929] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:53:08,942] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2024-12-14 15:53:42,770] {processor.py:153} INFO - Started process (PID=48624) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:53:42,771] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 15:53:42,772] {logging_mixin.py:115} INFO - [2024-12-14 15:53:42,772] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:53:42,800] {logging_mixin.py:115} INFO - [2024-12-14 15:53:42,800] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 15:53:42,800] {logging_mixin.py:115} INFO - [2024-12-14 15:53:42,800] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 15:53:42,801] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:53:42,813] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2024-12-14 15:54:18,654] {processor.py:153} INFO - Started process (PID=48753) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:54:18,655] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 15:54:18,656] {logging_mixin.py:115} INFO - [2024-12-14 15:54:18,656] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:54:18,673] {logging_mixin.py:115} INFO - [2024-12-14 15:54:18,673] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 15:54:18,673] {logging_mixin.py:115} INFO - [2024-12-14 15:54:18,673] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 15:54:18,673] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:54:18,691] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-12-14 15:54:53,564] {processor.py:153} INFO - Started process (PID=48882) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:54:53,565] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 15:54:53,568] {logging_mixin.py:115} INFO - [2024-12-14 15:54:53,567] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:54:53,588] {logging_mixin.py:115} INFO - [2024-12-14 15:54:53,588] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 15:54:53,588] {logging_mixin.py:115} INFO - [2024-12-14 15:54:53,588] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 15:54:53,588] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:54:53,606] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-12-14 15:55:26,554] {processor.py:153} INFO - Started process (PID=49004) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:55:26,556] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 15:55:26,557] {logging_mixin.py:115} INFO - [2024-12-14 15:55:26,557] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:55:26,587] {logging_mixin.py:115} INFO - [2024-12-14 15:55:26,587] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 15:55:26,588] {logging_mixin.py:115} INFO - [2024-12-14 15:55:26,587] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 15:55:26,588] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:55:26,603] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.055 seconds
[2024-12-14 15:56:02,715] {processor.py:153} INFO - Started process (PID=49134) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:56:02,717] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 15:56:02,717] {logging_mixin.py:115} INFO - [2024-12-14 15:56:02,717] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:56:02,738] {logging_mixin.py:115} INFO - [2024-12-14 15:56:02,737] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 15:56:02,738] {logging_mixin.py:115} INFO - [2024-12-14 15:56:02,738] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 15:56:02,738] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:56:02,755] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-12-14 15:56:36,615] {processor.py:153} INFO - Started process (PID=49262) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:56:36,616] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 15:56:36,617] {logging_mixin.py:115} INFO - [2024-12-14 15:56:36,617] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:56:36,639] {logging_mixin.py:115} INFO - [2024-12-14 15:56:36,639] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 15:56:36,639] {logging_mixin.py:115} INFO - [2024-12-14 15:56:36,639] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 15:56:36,639] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:56:36,652] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-12-14 15:57:13,079] {processor.py:153} INFO - Started process (PID=49449) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:57:13,080] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 15:57:13,081] {logging_mixin.py:115} INFO - [2024-12-14 15:57:13,080] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:57:13,102] {logging_mixin.py:115} INFO - [2024-12-14 15:57:13,102] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 15:57:13,103] {logging_mixin.py:115} INFO - [2024-12-14 15:57:13,103] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 15:57:13,103] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:57:13,116] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-12-14 15:57:49,394] {processor.py:153} INFO - Started process (PID=49585) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:57:49,395] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 15:57:49,396] {logging_mixin.py:115} INFO - [2024-12-14 15:57:49,396] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:57:49,419] {logging_mixin.py:115} INFO - [2024-12-14 15:57:49,419] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 15:57:49,419] {logging_mixin.py:115} INFO - [2024-12-14 15:57:49,419] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 15:57:49,420] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:57:49,437] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2024-12-14 15:58:21,986] {processor.py:153} INFO - Started process (PID=49699) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:58:21,989] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 15:58:21,990] {logging_mixin.py:115} INFO - [2024-12-14 15:58:21,990] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:58:22,014] {logging_mixin.py:115} INFO - [2024-12-14 15:58:22,013] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 15:58:22,014] {logging_mixin.py:115} INFO - [2024-12-14 15:58:22,014] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 15:58:22,014] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:58:22,032] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2024-12-14 15:58:55,045] {processor.py:153} INFO - Started process (PID=49821) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:58:55,046] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 15:58:55,047] {logging_mixin.py:115} INFO - [2024-12-14 15:58:55,047] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:58:55,075] {logging_mixin.py:115} INFO - [2024-12-14 15:58:55,074] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 15:58:55,075] {logging_mixin.py:115} INFO - [2024-12-14 15:58:55,075] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 15:58:55,075] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:58:55,089] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2024-12-14 15:59:31,618] {processor.py:153} INFO - Started process (PID=49957) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:59:31,620] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 15:59:31,621] {logging_mixin.py:115} INFO - [2024-12-14 15:59:31,621] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:59:31,648] {logging_mixin.py:115} INFO - [2024-12-14 15:59:31,648] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 15:59:31,648] {logging_mixin.py:115} INFO - [2024-12-14 15:59:31,648] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 15:59:31,648] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 15:59:31,666] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.055 seconds
[2024-12-14 16:00:06,773] {processor.py:153} INFO - Started process (PID=50085) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:00:06,774] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:00:06,775] {logging_mixin.py:115} INFO - [2024-12-14 16:00:06,775] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:00:06,794] {logging_mixin.py:115} INFO - [2024-12-14 16:00:06,793] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:00:06,794] {logging_mixin.py:115} INFO - [2024-12-14 16:00:06,794] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:00:06,794] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:00:06,807] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-12-14 16:00:39,876] {processor.py:153} INFO - Started process (PID=50206) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:00:39,877] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:00:39,878] {logging_mixin.py:115} INFO - [2024-12-14 16:00:39,878] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:00:39,907] {logging_mixin.py:115} INFO - [2024-12-14 16:00:39,907] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:00:39,908] {logging_mixin.py:115} INFO - [2024-12-14 16:00:39,907] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:00:39,908] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:00:39,922] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2024-12-14 16:01:18,829] {processor.py:153} INFO - Started process (PID=50511) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:01:18,830] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:01:18,831] {logging_mixin.py:115} INFO - [2024-12-14 16:01:18,831] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:01:18,852] {logging_mixin.py:115} INFO - [2024-12-14 16:01:18,851] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:01:18,852] {logging_mixin.py:115} INFO - [2024-12-14 16:01:18,852] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:01:18,852] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:01:18,870] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2024-12-14 16:01:55,965] {processor.py:153} INFO - Started process (PID=50648) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:01:55,967] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:01:55,969] {logging_mixin.py:115} INFO - [2024-12-14 16:01:55,968] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:01:55,988] {logging_mixin.py:115} INFO - [2024-12-14 16:01:55,988] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:01:55,988] {logging_mixin.py:115} INFO - [2024-12-14 16:01:55,988] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:01:55,988] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:01:56,004] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-12-14 16:02:28,931] {processor.py:153} INFO - Started process (PID=50827) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:02:28,932] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:02:28,932] {logging_mixin.py:115} INFO - [2024-12-14 16:02:28,932] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:02:28,952] {logging_mixin.py:115} INFO - [2024-12-14 16:02:28,952] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:02:28,952] {logging_mixin.py:115} INFO - [2024-12-14 16:02:28,952] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:02:28,953] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:02:28,966] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2024-12-14 16:03:02,081] {processor.py:153} INFO - Started process (PID=50949) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:03:02,083] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:03:02,083] {logging_mixin.py:115} INFO - [2024-12-14 16:03:02,083] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:03:02,102] {logging_mixin.py:115} INFO - [2024-12-14 16:03:02,101] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:03:02,102] {logging_mixin.py:115} INFO - [2024-12-14 16:03:02,102] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:03:02,102] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:03:02,116] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-12-14 16:03:36,715] {processor.py:153} INFO - Started process (PID=51079) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:03:36,717] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:03:36,718] {logging_mixin.py:115} INFO - [2024-12-14 16:03:36,718] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:03:36,750] {logging_mixin.py:115} INFO - [2024-12-14 16:03:36,749] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:03:36,751] {logging_mixin.py:115} INFO - [2024-12-14 16:03:36,750] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:03:36,751] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:03:36,772] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2024-12-14 16:04:09,868] {processor.py:153} INFO - Started process (PID=51197) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:04:09,868] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:04:09,869] {logging_mixin.py:115} INFO - [2024-12-14 16:04:09,869] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:04:09,892] {logging_mixin.py:115} INFO - [2024-12-14 16:04:09,892] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:04:09,892] {logging_mixin.py:115} INFO - [2024-12-14 16:04:09,892] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:04:09,893] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:04:09,910] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2024-12-14 16:04:47,120] {processor.py:153} INFO - Started process (PID=51330) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:04:47,122] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:04:47,123] {logging_mixin.py:115} INFO - [2024-12-14 16:04:47,123] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:04:47,146] {logging_mixin.py:115} INFO - [2024-12-14 16:04:47,146] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:04:47,146] {logging_mixin.py:115} INFO - [2024-12-14 16:04:47,146] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:04:47,147] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:04:47,161] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2024-12-14 16:05:20,359] {processor.py:153} INFO - Started process (PID=51452) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:05:20,360] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:05:20,360] {logging_mixin.py:115} INFO - [2024-12-14 16:05:20,360] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:05:20,380] {logging_mixin.py:115} INFO - [2024-12-14 16:05:20,380] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:05:20,381] {logging_mixin.py:115} INFO - [2024-12-14 16:05:20,381] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:05:20,381] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:05:20,394] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-12-14 16:05:54,622] {processor.py:153} INFO - Started process (PID=51580) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:05:54,624] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:05:54,625] {logging_mixin.py:115} INFO - [2024-12-14 16:05:54,625] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:05:54,644] {logging_mixin.py:115} INFO - [2024-12-14 16:05:54,644] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:05:54,645] {logging_mixin.py:115} INFO - [2024-12-14 16:05:54,644] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:05:54,645] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:05:54,663] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2024-12-14 16:06:27,997] {processor.py:153} INFO - Started process (PID=51761) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:06:27,998] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:06:27,999] {logging_mixin.py:115} INFO - [2024-12-14 16:06:27,999] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:06:28,023] {logging_mixin.py:115} INFO - [2024-12-14 16:06:28,022] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:06:28,023] {logging_mixin.py:115} INFO - [2024-12-14 16:06:28,023] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:06:28,023] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:06:28,041] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2024-12-14 16:07:03,907] {processor.py:153} INFO - Started process (PID=51889) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:07:03,907] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:07:03,908] {logging_mixin.py:115} INFO - [2024-12-14 16:07:03,908] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:07:03,927] {logging_mixin.py:115} INFO - [2024-12-14 16:07:03,926] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:07:03,927] {logging_mixin.py:115} INFO - [2024-12-14 16:07:03,927] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:07:03,927] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:07:03,941] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2024-12-14 16:07:36,347] {processor.py:153} INFO - Started process (PID=52063) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:07:36,349] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:07:36,350] {logging_mixin.py:115} INFO - [2024-12-14 16:07:36,350] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:07:36,376] {logging_mixin.py:115} INFO - [2024-12-14 16:07:36,375] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:07:36,376] {logging_mixin.py:115} INFO - [2024-12-14 16:07:36,376] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:07:36,376] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:07:36,388] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2024-12-14 16:08:06,952] {processor.py:153} INFO - Started process (PID=52184) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:08:06,953] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:08:06,954] {logging_mixin.py:115} INFO - [2024-12-14 16:08:06,954] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:08:06,975] {logging_mixin.py:115} INFO - [2024-12-14 16:08:06,974] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:08:06,975] {logging_mixin.py:115} INFO - [2024-12-14 16:08:06,975] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:08:06,975] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:08:06,989] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-12-14 16:08:37,163] {processor.py:153} INFO - Started process (PID=52414) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:08:37,164] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:08:37,164] {logging_mixin.py:115} INFO - [2024-12-14 16:08:37,164] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:08:37,187] {logging_mixin.py:115} INFO - [2024-12-14 16:08:37,186] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:08:37,187] {logging_mixin.py:115} INFO - [2024-12-14 16:08:37,187] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:08:37,187] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:08:37,201] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-12-14 16:09:12,071] {processor.py:153} INFO - Started process (PID=52651) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:09:12,072] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:09:12,075] {logging_mixin.py:115} INFO - [2024-12-14 16:09:12,074] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:09:12,097] {logging_mixin.py:115} INFO - [2024-12-14 16:09:12,097] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:09:12,097] {logging_mixin.py:115} INFO - [2024-12-14 16:09:12,097] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:09:12,098] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:09:12,117] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2024-12-14 16:09:43,497] {processor.py:153} INFO - Started process (PID=52764) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:09:43,498] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:09:43,498] {logging_mixin.py:115} INFO - [2024-12-14 16:09:43,498] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:09:43,518] {logging_mixin.py:115} INFO - [2024-12-14 16:09:43,518] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:09:43,518] {logging_mixin.py:115} INFO - [2024-12-14 16:09:43,518] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:09:43,519] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:09:43,532] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2024-12-14 16:10:17,584] {processor.py:153} INFO - Started process (PID=52892) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:10:17,585] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:10:17,586] {logging_mixin.py:115} INFO - [2024-12-14 16:10:17,586] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:10:17,606] {logging_mixin.py:115} INFO - [2024-12-14 16:10:17,606] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:10:17,606] {logging_mixin.py:115} INFO - [2024-12-14 16:10:17,606] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:10:17,607] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:10:17,620] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2024-12-14 16:10:51,808] {processor.py:153} INFO - Started process (PID=53129) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:10:51,808] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:10:51,809] {logging_mixin.py:115} INFO - [2024-12-14 16:10:51,809] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:10:51,827] {logging_mixin.py:115} INFO - [2024-12-14 16:10:51,826] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:10:51,827] {logging_mixin.py:115} INFO - [2024-12-14 16:10:51,827] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:10:51,827] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:10:51,841] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-12-14 16:11:22,387] {processor.py:153} INFO - Started process (PID=53244) to work on /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:11:22,389] {processor.py:641} INFO - Processing file /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-14 16:11:22,390] {logging_mixin.py:115} INFO - [2024-12-14 16:11:22,390] {dagbag.py:507} INFO - Filling up the DagBag from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:11:22,414] {logging_mixin.py:115} INFO - [2024-12-14 16:11:22,414] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-14 16:11:22,415] {logging_mixin.py:115} INFO - [2024-12-14 16:11:22,415] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-14 16:11:22,415] {processor.py:653} WARNING - No viable dags retrieved from /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-14 16:11:22,429] {processor.py:161} INFO - Processing /home/dev/curso/ambientevirtual/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
